name: saudi_digital_packet_tracer
description: A Packet Tracer Simulator.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.0.0
  path_provider: ^2.1.1
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/ic_launcher.png
    - assets/images/router.png
    - assets/images/pc.png
    - assets/images/laptop.png
    - assets/images/switch.png
    - assets/images/server.png